### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by revolter** [delfoxie/EclipseJavaFormatter#4]
I get this error when trying to run it:

```
Traceback (most recent call last):
  File ".\EclipseJavaFormatter.py", line 34, in run_
  File ".\EclipseJavaFormatter.py", line 57, in __run_external_command
  File ".\subprocess.py", line 633, in __init__
  File ".\subprocess.py", line 842, in _execute_child
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by delfoxie** [comment]
I have a couple of questions:
- are you running st2 or st3?
- have you set `eclipse_command` in your preferences?

**Comment by revolter** [comment]
I run st2 but I didn't have `eclipse_command` set and now it works. But I'm sure it did work some time ago, did the property gets reset when the plugin is updated? If yes, where can I set it up so it doesn't get overided? Thanks.

**Comment by delfoxie** [comment]
Hmm. I didn’t mess with the master code until I merged the st3 stuff in today. Did something change with your path and/or your eclipse installation recently?

**Comment by revolter** [comment]
Uhm, I did installed `Eclipse Kepler` version but I still have the previous version installed. I really can't remember what else I did but I'm pretty sure it's my fault :) So you can delete this topic altogether. Thanks for the help.
